### ISSUE TITLE
undefined method oauth_token= for #

### ISSUE THREAD

**Issue by antongiac** [rainersigwald/twitter_archiver#1]
Hello, when I run the script I got the following error
archiveTweets.rb:42:in `block in <main>': undefined method `oauth_token=' for #<Twitter::REST::Client:0x000000059b6658> (NoMethodError)
        from C:/Users/Giacomo/.gem/ruby/2.3.0/gems/twitter-6.2.0/lib/twitter/client.rb:19:in `initialize'
        from archiveTweets.rb:39:in `new'
        from archiveTweets.rb:39:in `<main>'
Do you know what I am doing wrong?
thanks for the great script

**Comment by agoddard** [comment]
@antongiac looks like it's not compatible with the latest version of the twitter Gem. I had luck just using an older version (`5.16.0`) of the Twitter gem
